#----------------------------------------------------------------------
#  _                                     _           
# | |    __ _ _   _  ___ _ __ _ __ _   _| | ___  ___ 
# | |   / _` | | | |/ _ \ '__| '__| | | | |/ _ \/ __|
# | |__| (_| | |_| |  __/ |  | |  | |_| | |  __/\__ \
# |_____\__,_|\__, |\___|_|  |_|   \__,_|_|\___||___/
#             |___/                                  

#----------------------------------------------------------------------

# Wlogout
layerrule {
        name = Wlogout-Animation
        match:namespace = logout_dialog
        animation = fade
}

# Slurp
layerrule {
        name = Slurp-Animation
        match:namespace = selection
        animation = fade
}

# Rofi
layerrule {
        name = Rofi-Animation
        match:namespace = rofi
        animation = popin
}

# Hyprpicker
layerrule {
        name = Hyprpicker-Animation
        match:namespace = hyprpicker
        animation = fade
}
