# ~/.config/hypr/hyprpaper.conf
preload = /home/yannick/Wallpaper/astronaut-in-field.png
wallpaper = eDP-1,/home/yannick/Wallpaper/astronaut-in-field.png
wallpaper = HDMI-A-1,/home/yannick/Wallpaper/astronaut-in-field.png
splash = false
