# ~/.config/hypr/hyprpaper.conf
preload = $HOME/Bilder/wallpapers/field-girl2.png.png
wallpaper = DP-1,$HOME/Bilder/wallpapers/field-girl2.png.png,center
wallpaper = HDMI-A-1,$HOME/Bilder/wallpapers/field-girl2.png.png,center
splash = false
